/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MostJugs.java
 *
 * Created on 06-17-2011, 10:24:05 PM
 */

package ManejadorJugadores;


import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import CodigoJuego.Juego;
import Grafico.EspacioDeJuego;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;


/**
 *
 * @author Owner
 */
public class MostJugs extends javax.swing.JDialog {

    EspacioDeJuego ances;

    JugManager jm= new JugManager();
    String[] nombres;
    String selec;
    int modo= 0;
    /** Creates new form MostJugs */
    

  
    public MostJugs(java.awt.Frame parent, boolean modal, int modo ) {
        super(parent, modal);
        ances= (EspacioDeJuego) parent;

        this.modo=modo;
        nombres= jm.getSoloNombres();
        DefaultListModel mod= new DefaultListModel();
        for(int it=0; it<nombres.length;it++)
            mod.addElement(nombres[it]);
        initComponents();
        listadoBase.setModel(mod);
        if(modo==1){
            Sel.setVisible(false);
            Can.setVisible(false);
        }

        if(modo==2||modo==3){
            Titulo.setText("Seleccione Jugadores Para Juego.");
            listadoBase.setSelectionMode(2);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoBase = new javax.swing.JList();
        Sel = new javax.swing.JButton();
        Can = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18));

        Titulo.setText("Jugadores Activos");

        jButton1.setText("Mostrar Estadisticas de Jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listadoBase.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listadoBase.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listadoBaseValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listadoBase);

        Sel.setText("Seleccionar");
        Can.setText("Cancelar");

        Sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelActionPerformed(evt);
            }
        });

        Can.setText("Cancelar");
        Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Can)
                    .addComponent(Sel))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(Sel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Can)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoBaseValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listadoBaseValueChanged
        selec= nombres[listadoBase.getSelectedIndex()];
    }//GEN-LAST:event_listadoBaseValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(selec!=null){
            JugInfo inf= jm.getJI(selec);
            JIGraf jif= new JIGraf(null,true,inf);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void SelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelActionPerformed
        if(listadoBase.getSelectedIndices().length>=2){
            String[] jugs= new String[listadoBase.getSelectedIndices().length];
            for(int yi= 0; yi<jugs.length; yi++)
                jugs[yi]= nombres[listadoBase.getSelectedIndices()[yi]];
            if(modo== 2){
                ances.jueg= new Juego(jugs);
                ances.prepararJuego();
            }
       }
    }//GEN-LAST:event_SelActionPerformed

    private void CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CanActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostJugs dialog = new MostJugs(new javax.swing.JFrame(), true,3);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Can;
    private javax.swing.JButton Sel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listadoBase;
    // End of variables declaration//GEN-END:variables

}
