/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Partidas.java
 *
 * Created on 06-19-2011, 04:52:20 PM
 */

package Grafico;

import ManejadorPartidas.BitacoraPartidas;

import javax.swing.DefaultListModel;

import javax.swing.JList;

/**
 *
 * @author Owner
 */
public class Partidas extends javax.swing.JDialog {

    /** Creates new form Partidas */

    public Partidas(java.awt.Frame parent, boolean modal,int mode) {
        super(parent, modal);
        initComponents();
        if(mode==1){
            this.Encabezado.setText("Todas las partidas jugadas.");
            BitacoraPartidas bit= new BitacoraPartidas();
            String[] yip= bit.getReportes();
            DefaultListModel sony= new DefaultListModel();
            for(String j: yip)
                sony.addElement(j);
            Cuadro.setModel(sony);
        }
        if(mode==2){
            this.Encabezado.setText("Top 10");
            BitacoraPartidas bit= new BitacoraPartidas();
            String[] yip= bit.Top(10);
            DefaultListModel sony= new DefaultListModel();
            for(String j: yip)
                sony.addElement(j);
            Cuadro.setModel(sony);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Encabezado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cuadro = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Encabezado.setText("jLabel1");

        Cuadro.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Cuadro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

                .addGap(38, 38, 38)
                .addComponent(Encabezado)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Partidas dialog = new Partidas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Partidas dialog = new Partidas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Cuadro;
    private javax.swing.JLabel Encabezado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
